Merge seb-sandbox to master
sebferrer/jays pull request #5
Opened 2018-08-12 19:04 UTC by sebferrer

Sprites animations + Jays head dissociation

2018-08-12 23:05 UTC, bastienguillon requested changes

2018-08-12 23:05 UTC, bastienguillon commented on src/entity.ts
> +		this.current_sprite = current_sprite;
Les entités n'avaient pas besoin de manipuler des sprites jusqu'à maintenant, c'est vraiment nécessaire de mettre ça dans la classe abstraite ?

2018-08-12 23:05 UTC, bastienguillon commented on src/entity.ts
> +	public sprite_collecs: Map<string, Sprite[]>;
Ah, je connaissais pas la classe `Map`, cool

2018-08-12 23:05 UTC, bastienguillon commented on src/entity.ts
> +		for (var d = 0, len = SPRITES.length; d < len; d++) {
C'est bizarre de devoir parcourir toute la collection de SPRITES, surtout dans la classe Entité, ce n'est pas son rôle de faire ça

2018-08-12 23:05 UTC, bastienguillon commented on src/entity.ts
> +		this.current_sprite = current_sprite;
Il faudrait sans doute une classe abstraite intermédiaire

```TS
export abstract class EntityWithSprites extends Entity {
   // ...
} 
```

2018-08-12 23:05 UTC, bastienguillon commented on src/entity.ts
> +		for (var d = 0, len = SPRITES.length; d < len; d++) {
Ce serait peut-être plus pratique d'avoir un `SpriteHelper` qui contient des méthodes capable de te sortir le/les sprites qui t'intéressent en fonction de leur Id. `SPRITES` pourrait également être un dictionnaire non ? ça pourrait simplifier les choses

2018-08-12 23:05 UTC, bastienguillon commented on src/entity.ts
> +				for (let i = 0; i < SPRITES[d].collec_sprites.length; i++) {
Tu peux utiliser la méthode `map` pour faire ça en moins de lignes de codes

```TS
const sprite_collecs = SPRITES[d].collec_sprites.map((item, index => { return /* transformation de l'item */ });
```

2018-08-12 23:05 UTC, bastienguillon commented on src/entity.ts
> +	public has_collision_warp(direction: Direction, collision_warp: CollisionWarp) { }
cette méthode devra être abstraite une fois qu'`Entity` sera abstraite, c'est ça ?

2018-08-12 23:05 UTC, bastienguillon commented on src/enum.ts
> +export const Direction_Int = new Map<Direction, number>([
Cette Map ne sera utilisée que dans la classe `Jays` non ? Il faudrait peut-être la mettre dans le même fichier

2018-08-12 23:05 UTC, bastienguillon commented on src/gamestate.ts
> +				if (ArrayUtil.addFirstNoDuplicate(this.directions_keyDown, Direction.UP)) {
Ca me semble bizarre de faire ça directement dans le GameState, ce n'est pas faisable dans la méthode Jays.update() ? 

Je pense que les entités qui réagissent aux actions claviers devraient s'abonner au GameState, ça me semble être un bon cas ici pour mettre en place le design pattern observer, ça permettrait de réduire le couplage du gamestate vers les autres entités

```TS
export interface IKeyObserver {
   onKeyTop: () => void;
   onKeyBottom: () => void;
   onKeyLeft: () => void;
   onKeyRight: () => void;
   // Idem pour arrow, etc
}

export class Jay implements IKeyObserver {
   // ...
}

export class GameState {
   public keyObservers: IKeyObserver[];

   constructor() {
      this.keyObservers.push(this.jays);
   }

   public keyDown(keyname: string) {
       switch(keyName) {
           case "z":
               this.keyObservers.each(observer => observer.onKeyTop());
           break;
       }
   }
}


```

2018-08-12 23:05 UTC, bastienguillon commented on src/jays.ts
> +		gameState.direction_event.getAllDirectionsValues().forEach(function (dir_event_move) {
Pas besoin du mot clé `function` ici à priori

2018-08-12 23:05 UTC, bastienguillon commented on src/jays.ts
> +			if (timer_sprites.tick >= this.sprite_collecs.get(this.current_sprite.collec_id).length) {
tu peux réunir les deux `if` en un seul

2018-08-12 23:05 UTC, bastienguillon commented on src/jays.ts
> +			if (dir_event_move.enabled) {
Tu peux utiliser la méthode `Array.filter` ici : 

```TS
gameState.direction_event.getAllDirectionsValues()
   .filter(dir_event_move => dir_event_move.enabled)
   .forEach(dir_event_move => {
      // ...
   });
```

2018-08-12 23:05 UTC, bastienguillon commented on src/main.ts
> +	const jays = new Jays("jays", new Sprite(0, 20, 20, 20), 20, 20, canvas_W / 2 - 10, canvas_H / 2 - 20);
C'est bizarre d'avoir besoin d'un `new Sprite(0, 20, 20, 20)` et de tous ces paramètres pour instancier la classe `Jays` non ? La classe `Jays` pourrait déclarer ça toute seule et les passer dans son constructeur à la méthode `super()` non ?

2018-08-12 23:05 UTC, bastienguillon commented on src/room_map.ts
> +export class RoomMap {
ça faisait des collisions avec la classe `Map`? :stuck_out_tongue:

2018-08-12 23:05 UTC, bastienguillon commented on src/tear.ts
> +		super(id, current_sprite, width, height, pos_x, pos_y);
la classe `Tear` devrait être capable de sortir son `current_sprite` toute seule, ça ne devrait pas être à l'utilisateur de la classe de le deviner

2018-08-12 23:05 UTC, bastienguillon commented on tsconfig.json
> +		"target": "es2016",
what? Pourquoi t'as besoin de ça ? C'est la prochaine version d'ecmaScript, c'est pas géré partout

2018-08-12 23:42 UTC, sebferrer commented on src/entity.ts
> +	public sprite_collecs: Map<string, Sprite[]>;
Super pratique. C'est d'ailleurs pour ça que j'ai renommé notre ancienne classe Map en RoomMap

2018-08-12 23:53 UTC, sebferrer commented on src/entity.ts
> +		this.current_sprite = current_sprite;
Avant les sprites n'étaient pas du tout gérés. On avait juste le sprite_filemane, et le clipping était fait en dur dans le renderer. Ça permet de mettre à jour les sprites d'une Entity en passant par un update plutôt que de le faire directement dans le renderer. Absolument toutes les Entities auront un Sprite, du coup ça n'aurait pas trop de sens de créer une autre classe comme celle-ci

2018-08-12 23:55 UTC, sebferrer commented on src/entity.ts
> +		this.current_sprite = current_sprite;
Je vois que tu as mis un "s" à "Sprites", tu faisais peut-être référence à la ligne 29 ? Si oui c'est déjà plus légitime, mais çe ne me plaît toujours pas trop. J'aime bien l'idée que toute Entity ne soit pas bloqués à son rôle d'Entity figée et qu'elles soient toutes potentiellement animables

2018-08-12 23:56 UTC, sebferrer commented on src/entity.ts
> +		for (var d = 0, len = SPRITES.length; d < len; d++) {
Bonne idée. Idée qu'on pourrait même appliquer à tout ce qu'on décrit dans des JSON

2018-08-12 23:57 UTC, sebferrer commented on src/entity.ts
> +				for (let i = 0; i < SPRITES[d].collec_sprites.length; i++) {
Merci, je vais regarder ça !

2018-08-12 23:57 UTC, sebferrer commented on src/entity.ts
> +	public has_collision_warp(direction: Direction, collision_warp: CollisionWarp) { }
Exact, tout comme has_collision_map()

2018-08-13 00:01 UTC, sebferrer commented on src/enum.ts
> +export const Direction_Int = new Map<Direction, number>([
Bah justement, non. En l'occurrence elle m'a servi pour Jays, mais c'est surtout un mapping générique qui veut dire "dans tout le projet, telle direction correspond à tel entier" (et aussi tel string via l'autre mapping). Ça simplifie énormément le code d'avoir ce genre de mapping, ça permet d'éviter d'avoir des switchs à répétition. Par contre y'a peut-être mieux à faire dans ce sens-là, on pourrait probablement faire plus propre (une classe DirectionHelper avec des getters remplaçant les mappings peut-être ?)

2018-08-13 00:08 UTC, sebferrer commented on src/gamestate.ts
> +				if (ArrayUtil.addFirstNoDuplicate(this.directions_keyDown, Direction.UP)) {
Bien vu, mais va falloir qu'on en parle directement ;)
Je propose de laisser comme c'est pour ce merge vu que c'est un peu à part de cette PR, et qu'on fasse un commit dédié à cette modif, c'est pas anodin comme changement

2018-08-13 00:09 UTC, sebferrer commented on src/jays.ts
> +			if (timer_sprites.tick >= this.sprite_collecs.get(this.current_sprite.collec_id).length) {
Exact !

2018-08-13 00:11 UTC, sebferrer commented on src/jays.ts
> +		gameState.direction_event.getAllDirectionsValues().forEach(function (dir_event_move) {
Je t'avoue que je n'ai pas beaucoup utilisé forEach en JS, donc je me suis contenté de suivre la doc. Je vais vérifier et modifierai si c'est possible

2018-08-13 00:12 UTC, sebferrer commented on src/jays.ts
> +			if (dir_event_move.enabled) {
Ah je ne connaissais pas, cool !

2018-08-13 00:14 UTC, sebferrer commented on src/main.ts
> +	const jays = new Jays("jays", new Sprite(0, 20, 20, 20), 20, 20, canvas_W / 2 - 10, canvas_H / 2 - 20);
Tout à fait

2018-08-13 00:15 UTC, sebferrer commented on src/room_map.ts
> +export class RoomMap {
Bien vu ahah

2018-08-13 00:17 UTC, sebferrer commented on src/tear.ts
> +		super(id, current_sprite, width, height, pos_x, pos_y);
Bien vu. On peut d'ailleurs en dire de même des autres Entities

2018-08-13 00:20 UTC, sebferrer commented on tsconfig.json
> +		"target": "es2016",
Pour la fonction array.includes() que je trouve vachement pratique. D'ailleurs j'ai trouvé ça bizarre que cette fonction je soit pas reconnue en ES6.
Je me suis payé l'erreur "Property 'includes' does not exist on type string[]"

2018-08-13 09:32 UTC, sebferrer commented on src/entity.ts
> +		for (var d = 0, len = SPRITES.length; d < len; d++) {
Ah, le "bonne idée" était pour le Helper. Pour le dictionnaire, ça simplifierait les choses mais limiterait ce qu'on peut faire avec, je prefère rester au JSON.

2018-08-13 10:07 UTC, bastienguillon commented on src/entity.ts
> +		for (var d = 0, len = SPRITES.length; d < len; d++) {
De toute façon `sprite_id` est commun entre plusieurs entrées de la collection `SPRITES`, donc ce n'est pas faisable

2018-08-13 10:11 UTC, bastienguillon commented on tsconfig.json
> +		"target": "es2016",
C'est dommage de réduire la compatibilité du projet pour une seule méthode :/

Tu peux utiliser  `maCollection.find(item => item.id === xxx) != null` pour faire sensiblement la même chose.

Ou sinon, si tu veux faire pas mal d'opérations sur des collections, on pourrait également utiliser une lib comme [Lodash](https://github.com/lodash/lodash), même si c'est sans doute un peu overkill

2018-08-13 10:18 UTC, sebferrer commented on tsconfig.json
> +		"target": "es2016",
Je suis d'accord que c'est carrément dommage.
Par contre ce qui est bien avec includes c'est qu'on peut lui passer un array en paramètre, et pas seulement une simple variable.
Lodash juste pour ça c'est un peu overkill effectivement

Je propose de recoder includes nous-même dans le ArrayUtil

2018-08-13 10:58 UTC, bastienguillon commented on tsconfig.json
> +		"target": "es2016",
Qu'est ce que tu veux dire par 'on peut lui passer un array en paramètre' ?

2018-08-13 12:35 UTC, sebferrer commented on src/tear.ts
> +		super(id, current_sprite, width, height, pos_x, pos_y);
D'ailleurs j'en profite pour signaler que depuis le début, les paramètres d'une Entity sont dans l'ordre (width, height, pos_x, pos_y)
J'sais pas pourquoi j'ai fait ça quand j'ai commencé, c'est pas cohérent du tout avec le reste.
J'ai changé à (pos_x, pos_y, width, height)

2018-08-13 12:42 UTC, sebferrer commented on tsconfig.json
> +		"target": "es2016",
Laisse tomber j'ai dis de la merde, j'ai confondu avec autre chose (et un autre besoin en plus AHAHAHAHAH)

Va pour le find.

2018-08-13 12:49 UTC, sebferrer commented on tsconfig.json
> +		"target": "es2016",
Quoique find c'est pour les collections, là j'en ai juste besoin pour des arrays.
On va partir sur un bon vieux indexOf. J'ai jamais trouvé ça joli mais au moins ça marche partout

2018-08-13 13:25 UTC, bastienguillon commented on tsconfig.json
> +		"target": "es2016",
> find c'est pour les collections, là j'en ai juste besoin pour des arrays
Faut que tu dormes plus

2018-08-13 13:28 UTC, sebferrer commented on tsconfig.json
> +		"target": "es2016",
Pour les collections D'OBJETS, j'en ai juste besoin pour les arrays DE STRINGS
Faut surtout que j'apprenne à ne pas oublier un mot sur deux quand j'écris

2018-08-13 21:55 UTC, bastienguillon approved these changes
C'est bon pour le linter finalement !

2018-08-13 21:55 UTC, merged